// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDxy62iO-NckFSPUQDCUo94EQx7v4l8fE',
    appId: '1:118127339712:web:c61105dcf71601630ce525',
    messagingSenderId: '118127339712',
    projectId: 'buffme-cd886',
    authDomain: 'buffme-cd886.firebaseapp.com',
    storageBucket: 'buffme-cd886.firebasestorage.app',
    measurementId: 'G-T63RWEWD7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAQUk1oC4dJk_lqzDN2U_1NKsw2c6hzdk',
    appId: '1:118127339712:android:65c518b86b2470b70ce525',
    messagingSenderId: '118127339712',
    projectId: 'buffme-cd886',
    storageBucket: 'buffme-cd886.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5EdyK4Wi7HNnMkdvoDHY1x0vAoOgKUsE',
    appId: '1:118127339712:ios:ff369625a1db30b70ce525',
    messagingSenderId: '118127339712',
    projectId: 'buffme-cd886',
    storageBucket: 'buffme-cd886.firebasestorage.app',
    iosBundleId: 'com.example.buffMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5EdyK4Wi7HNnMkdvoDHY1x0vAoOgKUsE',
    appId: '1:118127339712:ios:ff369625a1db30b70ce525',
    messagingSenderId: '118127339712',
    projectId: 'buffme-cd886',
    storageBucket: 'buffme-cd886.firebasestorage.app',
    iosBundleId: 'com.example.buffMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDxy62iO-NckFSPUQDCUo94EQx7v4l8fE',
    appId: '1:118127339712:web:d5dd1872a6f1cd1c0ce525',
    messagingSenderId: '118127339712',
    projectId: 'buffme-cd886',
    authDomain: 'buffme-cd886.firebaseapp.com',
    storageBucket: 'buffme-cd886.firebasestorage.app',
    measurementId: 'G-THJDYC6JG4',
  );

}